//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.06 at 01:03:03 AM CET 
//


package com.zavod.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zavod.autorska package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TLicePseudonim_QNAME = new QName("http://www.zavod.com/Autorska", "pseudonim");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zavod.autorska
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TDelo }
     * 
     */
    public TDelo createTDelo() {
        return new TDelo();
    }

    /**
     * Create an instance of {@link Zahtevi }
     * 
     */
    public Zahtevi createZahtevi() {
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link TZahtev }
     * 
     */
    public TZahtev createTZahtev() {
        return new TZahtev();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TInformacijeZavoda }
     * 
     */
    public TInformacijeZavoda createTInformacijeZavoda() {
        return new TInformacijeZavoda();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zavod.com/Autorska", name = "pseudonim", scope = TLice.class)
    public JAXBElement<String> createTLicePseudonim(String value) {
        return new JAXBElement<String>(_TLicePseudonim_QNAME, String.class, TLice.class, value);
    }

}
