//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.15 at 12:33:55 AM CET 
//


package com.zavod.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDelo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDelo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alternativni_naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vrsta_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="forma_zapisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="radni_odnos" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nacin_koriscenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Prerada" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="originalni_naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Originalni_Autor">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDelo", propOrder = {
    "naslov",
    "alternativniNaslov",
    "vrstaDela",
    "formaZapisa",
    "radniOdnos",
    "nacinKoriscenja",
    "prerada"
})
public class TDelo {

    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(name = "alternativni_naslov", required = true)
    protected String alternativniNaslov;
    @XmlElement(name = "vrsta_dela", required = true)
    protected String vrstaDela;
    @XmlElement(name = "forma_zapisa", required = true)
    protected String formaZapisa;
    @XmlElement(name = "radni_odnos")
    protected boolean radniOdnos;
    @XmlElement(name = "nacin_koriscenja", required = true)
    protected String nacinKoriscenja;
    @XmlElement(name = "Prerada")
    protected Prerada prerada;

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the alternativniNaslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativniNaslov() {
        return alternativniNaslov;
    }

    /**
     * Sets the value of the alternativniNaslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativniNaslov(String value) {
        this.alternativniNaslov = value;
    }

    /**
     * Gets the value of the vrstaDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaDela() {
        return vrstaDela;
    }

    /**
     * Sets the value of the vrstaDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaDela(String value) {
        this.vrstaDela = value;
    }

    /**
     * Gets the value of the formaZapisa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaZapisa() {
        return formaZapisa;
    }

    /**
     * Sets the value of the formaZapisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaZapisa(String value) {
        this.formaZapisa = value;
    }

    /**
     * Gets the value of the radniOdnos property.
     * 
     */
    public boolean isRadniOdnos() {
        return radniOdnos;
    }

    /**
     * Sets the value of the radniOdnos property.
     * 
     */
    public void setRadniOdnos(boolean value) {
        this.radniOdnos = value;
    }

    /**
     * Gets the value of the nacinKoriscenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinKoriscenja() {
        return nacinKoriscenja;
    }

    /**
     * Sets the value of the nacinKoriscenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinKoriscenja(String value) {
        this.nacinKoriscenja = value;
    }

    /**
     * Gets the value of the prerada property.
     * 
     * @return
     *     possible object is
     *     {@link Prerada }
     *     
     */
    public Prerada getPrerada() {
        return prerada;
    }

    /**
     * Sets the value of the prerada property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prerada }
     *     
     */
    public void setPrerada(Prerada value) {
        this.prerada = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="originalni_naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Originalni_Autor">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalniNaslov",
        "originalniAutor"
    })
    public static class Prerada {

        @XmlElement(name = "originalni_naslov", required = true)
        protected String originalniNaslov;
        @XmlElement(name = "Originalni_Autor", required = true)
        protected OriginalniAutor originalniAutor;

        /**
         * Gets the value of the originalniNaslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalniNaslov() {
            return originalniNaslov;
        }

        /**
         * Sets the value of the originalniNaslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalniNaslov(String value) {
            this.originalniNaslov = value;
        }

        /**
         * Gets the value of the originalniAutor property.
         * 
         * @return
         *     possible object is
         *     {@link OriginalniAutor }
         *     
         */
        public OriginalniAutor getOriginalniAutor() {
            return originalniAutor;
        }

        /**
         * Sets the value of the originalniAutor property.
         * 
         * @param value
         *     allowed object is
         *     {@link OriginalniAutor }
         *     
         */
        public void setOriginalniAutor(OriginalniAutor value) {
            this.originalniAutor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime"
        })
        public static class OriginalniAutor {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

        }

    }

}
