//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.15 at 12:33:55 AM CET 
//


package com.zavod.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TInformacije_Zavoda complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInformacije_Zavoda">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.zavod.com/Autorska}broj_prijave"/>
 *         &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="prilozi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="primer_dela" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                   &lt;element name="opis_dela" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                   &lt;element name="punomocje" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                   &lt;element name="uplata" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInformacije_Zavoda", propOrder = {
    "brojPrijave",
    "datumPodnosenja",
    "prilozi"
})
public class TInformacijeZavoda {

    @XmlElement(name = "broj_prijave", required = true)
    protected String brojPrijave;
    @XmlElement(name = "datum_podnosenja", required = true)
    protected XMLGregorianCalendar datumPodnosenja;
    @XmlElement(required = true)
    protected Prilozi prilozi;

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    /**
     * Gets the value of the prilozi property.
     * 
     * @return
     *     possible object is
     *     {@link Prilozi }
     *     
     */
    public Prilozi getPrilozi() {
        return prilozi;
    }

    /**
     * Sets the value of the prilozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prilozi }
     *     
     */
    public void setPrilozi(Prilozi value) {
        this.prilozi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="primer_dela" type="{http://www.zavod.com/Autorska}TPrilog"/>
     *         &lt;element name="opis_dela" type="{http://www.zavod.com/Autorska}TPrilog"/>
     *         &lt;element name="punomocje" type="{http://www.zavod.com/Autorska}TPrilog"/>
     *         &lt;element name="uplata" type="{http://www.zavod.com/Autorska}TPrilog"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primerDela",
        "opisDela",
        "punomocje",
        "uplata"
    })
    public static class Prilozi {

        @XmlElement(name = "primer_dela", required = true)
        protected TPrilog primerDela;
        @XmlElement(name = "opis_dela", required = true)
        protected TPrilog opisDela;
        @XmlElement(required = true)
        protected TPrilog punomocje;
        @XmlElement(required = true)
        protected TPrilog uplata;

        /**
         * Gets the value of the primerDela property.
         * 
         * @return
         *     possible object is
         *     {@link TPrilog }
         *     
         */
        public TPrilog getPrimerDela() {
            return primerDela;
        }

        /**
         * Sets the value of the primerDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPrilog }
         *     
         */
        public void setPrimerDela(TPrilog value) {
            this.primerDela = value;
        }

        /**
         * Gets the value of the opisDela property.
         * 
         * @return
         *     possible object is
         *     {@link TPrilog }
         *     
         */
        public TPrilog getOpisDela() {
            return opisDela;
        }

        /**
         * Sets the value of the opisDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPrilog }
         *     
         */
        public void setOpisDela(TPrilog value) {
            this.opisDela = value;
        }

        /**
         * Gets the value of the punomocje property.
         * 
         * @return
         *     possible object is
         *     {@link TPrilog }
         *     
         */
        public TPrilog getPunomocje() {
            return punomocje;
        }

        /**
         * Sets the value of the punomocje property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPrilog }
         *     
         */
        public void setPunomocje(TPrilog value) {
            this.punomocje = value;
        }

        /**
         * Gets the value of the uplata property.
         * 
         * @return
         *     possible object is
         *     {@link TPrilog }
         *     
         */
        public TPrilog getUplata() {
            return uplata;
        }

        /**
         * Sets the value of the uplata property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPrilog }
         *     
         */
        public void setUplata(TPrilog value) {
            this.uplata = value;
        }

    }

}
