//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.06 at 01:03:03 AM CET 
//


package com.zavod.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TInformacije_Zavoda complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInformacije_Zavoda">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="opis_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primer_dela" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="broj_prijave">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="A-[0-9]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum_podsnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInformacije_Zavoda", propOrder = {
    "opisDela",
    "primerDela",
    "brojPrijave",
    "datumPodsnosenja"
})
public class TInformacijeZavoda {

    @XmlElement(name = "opis_dela", required = true)
    protected String opisDela;
    @XmlElement(name = "primer_dela", required = true)
    protected Object primerDela;
    @XmlElement(name = "broj_prijave", required = true)
    protected String brojPrijave;
    @XmlElement(name = "datum_podsnosenja", required = true)
    protected XMLGregorianCalendar datumPodsnosenja;

    /**
     * Gets the value of the opisDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisDela() {
        return opisDela;
    }

    /**
     * Sets the value of the opisDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisDela(String value) {
        this.opisDela = value;
    }

    /**
     * Gets the value of the primerDela property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPrimerDela() {
        return primerDela;
    }

    /**
     * Sets the value of the primerDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPrimerDela(Object value) {
        this.primerDela = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodsnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodsnosenja() {
        return datumPodsnosenja;
    }

    /**
     * Sets the value of the datumPodsnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodsnosenja(XMLGregorianCalendar value) {
        this.datumPodsnosenja = value;
    }

}
