//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 10:43:35 PM CET 
//


package com.zavod.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPravno_Lice", propOrder = {
    "ime",
    "telefon",
    "email",
    "pseudonim",
    "sediste"
})
public class TPravnoLice extends TLice
{

    @XmlElement(required = true)
    protected String sediste;

    public String getSediste() {
        return sediste;
    }

    public void setSediste(String value) {
        this.sediste = value;
    }

}
