//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.14 at 03:49:29 PM CET 
//


package com.zavod.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TZahtev complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TZahtev">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Podnosilac" type="{http://www.zavod.com/Autorska}TLice"/>
 *         &lt;element name="Delo" type="{http://www.zavod.com/Autorska}TDelo"/>
 *         &lt;element name="Autor" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.zavod.com/Autorska}TLice">
 *                 &lt;sequence>
 *                   &lt;element name="anoniman" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="godina_smrti" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Informacije_Zavoda" type="{http://www.zavod.com/Autorska}TInformacije_Zavoda"/>
 *         &lt;element name="Punomocnik" type="{http://www.zavod.com/Autorska}TFizicko_Lice" minOccurs="0"/>
 *         &lt;element name="Informacije_Sistema" type="{http://www.zavod.com/Autorska}TInformacije_Sistema" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TZahtev", propOrder = {
    "podnosilac",
    "delo",
    "autor",
    "informacijeZavoda",
    "punomocnik",
    "informacijeSistema"
})
@XmlRootElement(name = "Zahtev")
public class TZahtev {

    @XmlElement(name = "Podnosilac", required = true)
    protected TLice podnosilac;
    @XmlElement(name = "Delo", required = true)
    protected TDelo delo;
    @XmlElement(name = "Autor")
    protected Autor autor;
    @XmlElement(name = "Informacije_Zavoda", required = true)
    protected TInformacijeZavoda informacijeZavoda;
    @XmlElement(name = "Punomocnik")
    protected TFizickoLice punomocnik;
    @XmlElement(name = "Informacije_Sistema")
    protected TInformacijeSistema informacijeSistema;

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the delo property.
     * 
     * @return
     *     possible object is
     *     {@link TDelo }
     *     
     */
    public TDelo getDelo() {
        return delo;
    }

    /**
     * Sets the value of the delo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDelo }
     *     
     */
    public void setDelo(TDelo value) {
        this.delo = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link Autor }
     *     
     */
    public Autor getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autor }
     *     
     */
    public void setAutor(Autor value) {
        this.autor = value;
    }

    /**
     * Gets the value of the informacijeZavoda property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacijeZavoda }
     *     
     */
    public TInformacijeZavoda getInformacijeZavoda() {
        return informacijeZavoda;
    }

    /**
     * Sets the value of the informacijeZavoda property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacijeZavoda }
     *     
     */
    public void setInformacijeZavoda(TInformacijeZavoda value) {
        this.informacijeZavoda = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPunomocnik(TFizickoLice value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the informacijeSistema property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacijeSistema }
     *     
     */
    public TInformacijeSistema getInformacijeSistema() {
        return informacijeSistema;
    }

    /**
     * Sets the value of the informacijeSistema property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacijeSistema }
     *     
     */
    public void setInformacijeSistema(TInformacijeSistema value) {
        this.informacijeSistema = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.zavod.com/Autorska}TLice">
     *       &lt;sequence>
     *         &lt;element name="anoniman" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="godina_smrti" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "anoniman",
        "godinaSmrti"
    })
    public static class Autor
        extends TLice
    {

        @XmlElement(defaultValue = "false")
        protected boolean anoniman;
        @XmlElement(name = "godina_smrti")
        protected XMLGregorianCalendar godinaSmrti;

        /**
         * Gets the value of the anoniman property.
         * 
         */
        public boolean isAnoniman() {
            return anoniman;
        }

        /**
         * Sets the value of the anoniman property.
         * 
         */
        public void setAnoniman(boolean value) {
            this.anoniman = value;
        }

        /**
         * Gets the value of the godinaSmrti property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getGodinaSmrti() {
            return godinaSmrti;
        }

        /**
         * Sets the value of the godinaSmrti property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setGodinaSmrti(XMLGregorianCalendar value) {
            this.godinaSmrti = value;
        }

    }

}
