//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.25 at 03:07:21 PM CET 
//


package com.zavod.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zavod.zig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zahtev_QNAME = new QName("http://www.zavod.com/Zig", "Zahtev");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zavod.zig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TZig }
     * 
     */
    public TZig createTZig() {
        return new TZig();
    }

    /**
     * Create an instance of {@link TPrilog }
     * 
     */
    public TPrilog createTPrilog() {
        return new TPrilog();
    }

    /**
     * Create an instance of {@link TInformacijeZavoda }
     * 
     */
    public TInformacijeZavoda createTInformacijeZavoda() {
        return new TInformacijeZavoda();
    }

    /**
     * Create an instance of {@link TPlacanje }
     * 
     */
    public TPlacanje createTPlacanje() {
        return new TPlacanje();
    }

    /**
     * Create an instance of {@link TInformacijeZavoda.Prilozi }
     * 
     */
    public TInformacijeZavoda.Prilozi createTInformacijeZavodaPrilozi() {
        return new TInformacijeZavoda.Prilozi();
    }

    /**
     * Create an instance of {@link TZig.KlaseRobe }
     * 
     */
    public TZig.KlaseRobe createTZigKlaseRobe() {
        return new TZig.KlaseRobe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Zahtev }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zavod.com/Zig", name = "Zahtev")
    public JAXBElement<Zahtev> createZahtev(Zahtev value) {
        return new JAXBElement<Zahtev>(_Zahtev_QNAME, Zahtev.class, null, value);
    }

}
