//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 12:14:51 AM CET 
//


package com.zavod.model.zig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zavod.zig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zavod.zig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TInformacijeZavoda.Prilozi }
     * 
     */
    public TInformacijeZavoda.Prilozi createTInformacijeZavodaPrilozi() {
        return new TInformacijeZavoda.Prilozi();
    }

    /**
     * Create an instance of {@link TZig.KlaseRobe }
     * 
     */
    public TZig.KlaseRobe createTZigKlaseRobe() {
        return new TZig.KlaseRobe();
    }

    /**
     * Create an instance of {@link Zahtevi }
     * 
     */
    public Zahtevi createZahtevi() {
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link TInformacijeZavoda }
     * 
     */
    public TInformacijeZavoda createTInformacijeZavoda() {
        return new TInformacijeZavoda();
    }

    /**
     * Create an instance of {@link TZig }
     * 
     */
    public TZig createTZig() {
        return new TZig();
    }

    /**
     * Create an instance of {@link TPlacanje }
     * 
     */
    public TPlacanje createTPlacanje() {
        return new TPlacanje();
    }

    /**
     * Create an instance of {@link TZahtev }
     * 
     */
    public TZahtev createTZahtev() {
        return new TZahtev();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

}
