//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 12:14:51 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.zavod.com/Zig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zavod.model.zig;
