//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 06:22:34 PM CET 
//


package com.zavod.model.izvestaj;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TIzvestaj complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TIzvestaj">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="broj_podnetih">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="broj_prihvacenih">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="broj_odbijenih">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="datumDo" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="datumOd" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TIzvestaj", propOrder = {
    "brojPodnetih",
    "brojPrihvacenih",
    "brojOdbijenih"
})
@XmlRootElement(name = "Izvestaj")
public class Izvestaj {

    @XmlElement(name = "broj_podnetih")
    protected int brojPodnetih;
    @XmlElement(name = "broj_prihvacenih")
    protected int brojPrihvacenih;
    @XmlElement(name = "broj_odbijenih")
    protected int brojOdbijenih;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar datumOd;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar datumDo;

    public Izvestaj() {
    }

    public Izvestaj(int brojPodnetih, int brojPrihvacenih, int brojOdbijenih, XMLGregorianCalendar datumOd, XMLGregorianCalendar datumDo) {
        this.brojPodnetih = brojPodnetih;
        this.brojPrihvacenih = brojPrihvacenih;
        this.brojOdbijenih = brojOdbijenih;
        this.datumOd = datumOd;
        this.datumDo = datumDo;
    }

    /**
     * Gets the value of the brojPodnetih property.
     * 
     */
    public int getBrojPodnetih() {
        return brojPodnetih;
    }

    /**
     * Sets the value of the brojPodnetih property.
     * 
     */
    public void setBrojPodnetih(int value) {
        this.brojPodnetih = value;
    }

    /**
     * Gets the value of the brojPrihvacenih property.
     * 
     */
    public int getBrojPrihvacenih() {
        return brojPrihvacenih;
    }

    /**
     * Sets the value of the brojPrihvacenih property.
     * 
     */
    public void setBrojPrihvacenih(int value) {
        this.brojPrihvacenih = value;
    }

    /**
     * Gets the value of the brojOdbijenih property.
     * 
     */
    public int getBrojOdbijenih() {
        return brojOdbijenih;
    }

    /**
     * Sets the value of the brojOdbijenih property.
     * 
     */
    public void setBrojOdbijenih(int value) {
        this.brojOdbijenih = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDo(XMLGregorianCalendar value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOd(XMLGregorianCalendar value) {
        this.datumOd = value;
    }

}
