//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 06:22:34 PM CET 
//


package com.zavod.model.izvestaj;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zavod.izvestaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Izvestaj_QNAME = new QName("http://www.zavod.com/Izvestaj", "Izvestaj");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zavod.izvestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createTIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Izvestaj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zavod.com/Izvestaj", name = "Izvestaj")
    public JAXBElement<Izvestaj> createIzvestaj(Izvestaj value) {
        return new JAXBElement<Izvestaj>(_Izvestaj_QNAME, Izvestaj.class, null, value);
    }

}
