//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 10:43:35 PM CET 
//


package com.zavod.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDelo", propOrder = {
    "naslov",
    "alternativniNaslov",
    "vrstaDela",
    "formaZapisa",
    "radniOdnos",
    "nacinKoriscenja",
    "prerada"
})
public class TDelo {

    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(name = "alternativni_naslov", required = true)
    protected String alternativniNaslov;
    @XmlElement(name = "vrsta_dela", required = true)
    protected String vrstaDela;
    @XmlElement(name = "forma_zapisa", required = true)
    protected String formaZapisa;
    @XmlElement(name = "radni_odnos")
    protected boolean radniOdnos;
    @XmlElement(name = "nacin_koriscenja", required = true)
    protected String nacinKoriscenja;
    @XmlElement(name = "Prerada")
    protected Prerada prerada;

    public String getNaslov() {
        return naslov;
    }

    public void setNaslov(String value) {
        this.naslov = value;
    }

    public String getAlternativniNaslov() {
        return alternativniNaslov;
    }

    public void setAlternativniNaslov(String value) {
        this.alternativniNaslov = value;
    }

    public String getVrstaDela() {
        return vrstaDela;
    }

    public void setVrstaDela(String value) {
        this.vrstaDela = value;
    }

    public String getFormaZapisa() {
        return formaZapisa;
    }

    public void setFormaZapisa(String value) {
        this.formaZapisa = value;
    }

    public boolean isRadniOdnos() {
        return radniOdnos;
    }

    public void setRadniOdnos(boolean value) {
        this.radniOdnos = value;
    }

    public String getNacinKoriscenja() {
        return nacinKoriscenja;
    }

    public void setNacinKoriscenja(String value) {
        this.nacinKoriscenja = value;
    }

    public Prerada getPrerada() {
        return prerada;
    }

    public void setPrerada(Prerada value) {
        this.prerada = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalniNaslov",
        "originalniAutor"
    })
    public static class Prerada {

        @XmlElement(name = "originalni_naslov", required = true)
        protected String originalniNaslov;
        @XmlElement(name = "Originalni_Autor", required = true)
        protected OriginalniAutor originalniAutor;

        /**
         * Gets the value of the originalniNaslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalniNaslov() {
            return originalniNaslov;
        }

        /**
         * Sets the value of the originalniNaslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalniNaslov(String value) {
            this.originalniNaslov = value;
        }

        /**
         * Gets the value of the originalniAutor property.
         * 
         * @return
         *     possible object is
         *     {@link OriginalniAutor }
         *     
         */
        public OriginalniAutor getOriginalniAutor() {
            return originalniAutor;
        }

        /**
         * Sets the value of the originalniAutor property.
         * 
         * @param value
         *     allowed object is
         *     {@link OriginalniAutor }
         *     
         */
        public void setOriginalniAutor(OriginalniAutor value) {
            this.originalniAutor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime"
        })
        public static class OriginalniAutor {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

        }

    }

}
