//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 10:43:35 PM CET 
//


package com.zavod.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TInformacije_Zavoda complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInformacije_Zavoda">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="broj_prijave">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="A-[0-9]{4}-[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="prilozi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="primer_dela" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                   &lt;element name="opis_dela" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                   &lt;element name="punomocje" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                   &lt;element name="uplata" type="{http://www.zavod.com/Autorska}TPrilog"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInformacije_Zavoda", propOrder = {
    "brojPrijave",
    "datumPodnosenja",
    "prilozi"
})
public class TInformacijeZavoda {

    @XmlElement(name = "broj_prijave", required = true)
    protected String brojPrijave;
    @XmlElement(name = "datum_podnosenja", required = true)
    protected XMLGregorianCalendar datumPodnosenja;
    @XmlElement(required = true)
    protected Prilozi prilozi;

    public String getBrojPrijave() {
        return brojPrijave;
    }

    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    public Prilozi getPrilozi() {
        return prilozi;
    }


    public void setPrilozi(Prilozi value) {
        this.prilozi = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primerDela",
        "opisDela",
        "punomocje",
        "uplata"
    })
    public static class Prilozi {

        @XmlElement(name = "primer_dela", required = true)
        protected TPrilog primerDela;
        @XmlElement(name = "opis_dela", required = true)
        protected TPrilog opisDela;
        @XmlElement(required = true)
        protected TPrilog punomocje;
        @XmlElement(required = true)
        protected TPrilog uplata;

        public TPrilog getPrimerDela() {
            return primerDela;
        }

        public void setPrimerDela(TPrilog value) {
            this.primerDela = value;
        }

        public TPrilog getOpisDela() {
            return opisDela;
        }

        public void setOpisDela(TPrilog value) {
            this.opisDela = value;
        }

        public TPrilog getPunomocje() {
            return punomocje;
        }

        public void setPunomocje(TPrilog value) {
            this.punomocje = value;
        }

        public TPrilog getUplata() {
            return uplata;
        }

        public void setUplata(TPrilog value) {
            this.uplata = value;
        }

    }

}
