//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 10:43:35 PM CET 
//


package com.zavod.model.zahtev;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLice", propOrder = {
    "ime",
    "telefon",
    "email",
    "pseudonim"
})
@XmlTransient
@XmlSeeAlso({
    TFizickoLice.class,
    TPravnoLice.class
})
public abstract class TLice {

    @XmlElement(required = true)
    protected String ime;
    protected String telefon;
    protected String email;
    protected String pseudonim;

    public String getIme() {
        return ime;
    }


    public void setIme(String value) {
        this.ime = value;
    }

    public String getTelefon() {
        return telefon;
    }


    public void setTelefon(String value) {
        this.telefon = value;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getPseudonim() {
        return pseudonim;
    }

    public void setPseudonim(String value) {
        this.pseudonim = value;
    }

}
