//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 10:43:35 PM CET
//


package com.zavod.model.zahtev;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TZahtev", propOrder = {
        "podnosilac",
        "delo",
        "autor",
        "informacijeZavoda",
        "punomocnik",
        "informacijeSistema"
})
@XmlRootElement(name = "Zahtev")
public class Zahtev {

    @XmlElement(name = "Podnosilac", required = true)
    protected TLice podnosilac;
    @XmlElement(name = "Delo", required = true)
    protected TDelo delo;
    @XmlElement(name = "Autor")
    protected Autor autor;
    @XmlElement(name = "Informacije_Zavoda", required = true)
    protected TInformacijeZavoda informacijeZavoda;
    @XmlElement(name = "Punomocnik")
    protected TFizickoLice punomocnik;
    @XmlElement(name = "Informacije_Sistema", required = true)
    protected TInformacijeSistema informacijeSistema;

    public TLice getPodnosilac() {
        return podnosilac;
    }


    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }


    public TDelo getDelo() {
        return delo;
    }


    public void setDelo(TDelo value) {
        this.delo = value;
    }


    public Autor getAutor() {
        return autor;
    }


    public void setAutor(Autor value) {
        this.autor = value;
    }


    public TInformacijeZavoda getInformacijeZavoda() {
        return informacijeZavoda;
    }

    public void setInformacijeZavoda(TInformacijeZavoda value) {
        this.informacijeZavoda = value;
    }


    public TFizickoLice getPunomocnik() {
        return punomocnik;
    }

    public void setPunomocnik(TFizickoLice value) {
        this.punomocnik = value;
    }

    public TInformacijeSistema getInformacijeSistema() {
        return informacijeSistema;
    }

    public void setInformacijeSistema(TInformacijeSistema value) {
        this.informacijeSistema = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "godinaSmrti"
    })
    public static class Autor extends TFizickoLice
    {

        @XmlElement(name = "godina_smrti")
        protected XMLGregorianCalendar godinaSmrti;

        public XMLGregorianCalendar getGodinaSmrti() {
            return godinaSmrti;
        }

        public void setGodinaSmrti(XMLGregorianCalendar value) {
            this.godinaSmrti = value;
        }

    }

}
