//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.28 at 07:12:40 PM CET 
//


package com.zavod.model.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TOdluka complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TOdluka">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prihvacen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TOdluka", propOrder = {
    "datum",
    "obrazlozenje",
    "prihvacen",
    "dostavioPrimer",
    "dostavioOpis"
})
public class TOdluka {

    @XmlElement(required = true)
    protected XMLGregorianCalendar datum;
    @XmlElement(required = true)
    protected String obrazlozenje;
    @XmlElement(required = true)
    protected boolean prihvacen;
    @XmlElement(name = "dostavio_primer", required = true)
    protected boolean dostavioPrimer;
    @XmlElement(name = "dostavio_opis", required = true)
    protected boolean dostavioOpis;


    public TOdluka() {
    }

    public TOdluka(XMLGregorianCalendar datum, String obrazlozenje, boolean prihvacen, boolean dostavioPrimer, boolean dostavioOpis) {
        this.datum = datum;
        this.obrazlozenje = obrazlozenje;
        this.prihvacen = prihvacen;
        this.dostavioPrimer = dostavioPrimer;
        this.dostavioOpis = dostavioOpis;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObrazlozenje(String value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the prihvacen property.
     * 
     */
    public boolean isPrihvacen() {
        return prihvacen;
    }

    /**
     * Sets the value of the prihvacen property.
     * 
     */
    public void setPrihvacen(boolean value) {
        this.prihvacen = value;
    }

}
