//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.25 at 03:07:21 PM CET 
//


package com.zavod.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPlacanje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPlacanje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="taksa_klasa" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="taksa_grafickog_resenja" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ukupno" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPlacanje", propOrder = {
    "osnovnaTaksa",
    "taksaKlasa",
    "taksaGrafickogResenja",
    "ukupno"
})
public class TPlacanje {

    @XmlElement(name = "osnovna_taksa")
    protected float osnovnaTaksa;
    @XmlElement(name = "taksa_klasa")
    protected float taksaKlasa;
    @XmlElement(name = "taksa_grafickog_resenja")
    protected float taksaGrafickogResenja;
    protected float ukupno;

    /**
     * Gets the value of the osnovnaTaksa property.
     * 
     */
    public float getOsnovnaTaksa() {
        return osnovnaTaksa;
    }

    /**
     * Sets the value of the osnovnaTaksa property.
     * 
     */
    public void setOsnovnaTaksa(float value) {
        this.osnovnaTaksa = value;
    }

    /**
     * Gets the value of the taksaKlasa property.
     * 
     */
    public float getTaksaKlasa() {
        return taksaKlasa;
    }

    /**
     * Sets the value of the taksaKlasa property.
     * 
     */
    public void setTaksaKlasa(float value) {
        this.taksaKlasa = value;
    }

    /**
     * Gets the value of the taksaGrafickogResenja property.
     * 
     */
    public float getTaksaGrafickogResenja() {
        return taksaGrafickogResenja;
    }

    /**
     * Sets the value of the taksaGrafickogResenja property.
     * 
     */
    public void setTaksaGrafickogResenja(float value) {
        this.taksaGrafickogResenja = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     */
    public float getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     */
    public void setUkupno(float value) {
        this.ukupno = value;
    }

}
